function R = rotation_matrix(phi,theta,psi)
    
    cphi = cos(phi);
    sphi = sin(phi);
    R_roll = [...
          1,    0,      0;...
          0,    cphi,   sphi;...
          0,    -sphi,  cphi];

    ctheta = cos(theta);
    stheta = sin(theta);
    R_pitch = [...
          ctheta,   0,  -stheta;...
          0,        1,  0;...
          stheta,   0,  ctheta];

    cpsi = cos(psi);
    spsi = sin(psi);
    R_yaw = [...
          cpsi,     spsi,   0;...
          -spsi,    cpsi,   0;...
          0,        0,      1];

    R = R_roll * R_pitch * R_yaw;

end